version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: contest-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
